apiVersion: v1
kind: Secret
metadata:
  name: {{ template "helm-backend.secret-name" . }}
  # namespace: {{ .Values.namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}