apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.poller.config.name }}
  labels:
    group: {{ .Values.poller.group }}
data:
  mysql_username: {{ .Values.poller.database.user }}
  mysql_password: {{ .Values.poller.database.password }}
  MYSQL_HOST: {{ .Values.poller.database.host }}
  kafka: {{ .Values.poller.kafka.server }}