apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-poller-deployment
  labels:
    app: {{ .Values.poller.name }}
    tier: backend

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-poller-deployment
  minReplicas: {{ .Values.podAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.podAutoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.podAutoscaling.averageCPUUtilization }}