apiVersion: v1
kind: Service
metadata:
  name: "webapp-service"
spec:
  selector:
    app: {{ .Values.backend.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      name: http