apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-poller-deployment
  labels:
    app: {{ .Values.poller.name }}
    group: {{ .Values.poller.group }}
spec:
  replicas: {{ .Values.replicaCount }}
  progressDeadlineSeconds: {{ .Values.poller.progressDeadlineSeconds }}
  minReadySeconds: {{ .Values.poller.minReadySeconds }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.poller.maxSurge }}
      maxUnavailable: {{ .Values.poller.maxUnavailable }}
    type: {{ .Values.poller.deploymentType }}
  selector:
    matchLabels:
      app: {{ .Values.poller.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.poller.name }}
        group: {{ .Values.poller.group }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      serviceAccountName: poller
      containers:
        - name: {{ .Values.poller.name }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.CPU }}
            limits: 
              cpu: {{ .Values.resources.limits.CPU }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /readyStatus
              port: {{ .Values.poller.container.port }}
            initialDelaySeconds: {{ .Values.poller.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.poller.probe.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /healthStatus
              port: {{ .Values.poller.container.port }}
            initialDelaySeconds: {{ .Values.poller.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.poller.probe.liveness.periodSeconds }}
          ports:
            - containerPort: {{ .Values.poller.container.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.poller.config.name }}
      imagePullSecrets:
        - name: myregistrykey
